### ISSUE TITLE
ZIM: not sure where to find the format list

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#10]
Found some info here: http://gams.uni-graz.at/archive/objects/context:gams/methods/sdef:Context/get?mode=about&locale=en
but it doesn't cover all the formats listed in our spreadsheet.

I am interested in PDF today, and I'll just skip the format for now, because I would have to do a lot of guessing about the domains, etc.

**Comment by TomazErjavec** [comment]
I think you can easily close this issue, as GAMS is not a self-archiving repository, so they don't "accept" data (and formats) as such. In fact, the link above does say: "Data can only be deposited as part of a cooperation research project. Each project is accompanied by a metadata manager from the Centre to assist with the workflow, data modelling, deposition and publication process in the course of the project. "
In light of that, I'm not even sure it makes sense to include GAMS in the SIS.

**Comment by hannahedeland** [comment]
I believe the section "Which data formats are used?" includes the (main) recommended formats of GAMS, and I think this information would be really valuable for the SIS, since we also want to find out which formats are generally recommended by many centres, but we might need some clarification and maybe additions, yes. The sample deposition agreement states that "The Depositor will supply Content by means of a method, format and medium deemed acceptable by the Repository." and "The Depositor will provide metadata for the Content and the data streams corresponding to the specifications agreed upon with the repository." so I guess in a way they do (or don't) accept specific formats, even if they also assist with conversion workflows for project partners.

**Comment by TomazErjavec** [comment]
> I guess in a way they do (or don't) accept specific formats
I guess they do, although I doubt that they have an explicit list, and it might be more a case of deciding for each project separately, also on the basis of soft and contextual factors. Anyway, sure, it would be nice to have their requirements included too, I just think it might be difficult, esp. as the author of the system is about to retire.

**Comment by bansp** [comment]
Adding a link to the recommendations: https://gams.uni-graz.at/context:gams?mode=about&locale=en#formats
