### ISSUE TITLE
Bad ID for CLARIN.SI

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/standards#104]
CLARIN.SI has the identifier "CLARINSI", but we always use the dot, so, if possible, I would be happier if the ID is also CLARIN.SI (just as the other centres with the hyphen have also the hypehen in their identifier, eg. CLARIN-IS has the ID rCLARIN-IS)

**Comment by bansp** [comment]
Thanks, Tomaž. The IDs we use there are kept in sync with the CLARIN DB shorthand field (https://centres.clarin.eu/centre/30). I guess we can just as well diverge from that, since, for now, there is no automated synchronization between the two, but here's a thought: do you think you can get the DB to also reflect the preference you mention? 
That would be a bit of a roundabout way for the SIS to handle this issue ;-) , but it may also be a way for the centre to avoid being addressed as "CLARINSI" in the future, so overall, a better solution, I think.

**Comment by TomazErjavec** [comment]
> The IDs we use there are kept in sync with the CLARIN DB shorthand field (https://centres.clarin.eu/centre/30)

Yes, I thoughts so, but have never been happy with how the CLARIN DB has specified the CLARIN.SI identifier (or their description for that matter).

> there is no automated synchronization between the two

And I also thought that there isn't any :)

> do you think you can get the DB to also reflect the preference you mention?

I already tried years ago, but they said they can't do it, can't remember why anymore, either becuse the CLARINSI was specified in too many places, or because they can't have periods in their IDs.
