### ISSUE TITLE
Suggestion regarding the description of format ID="fCoNNL", commitId=c97eae3

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/standards#128]
**Format short name / ID**
Strictly speaking the format "CoNLL" does not exist, there is the old CoNLL-X (https://aclanthology.org/W06-2920.pdf) used in the 2006 CoNLL shared task, CoNLL-U (https://universaldependencies.org/format.html) as the standard format used by Universal Dependencies and CoNLL-U Plus (https://universaldependencies.org/ext-format.html) as the extended version of CoNLL-U. So, maybe 3 formats should be here instead of 1, or the one changed from CoNLL to CoNLL-U as this is by far most used one.

**Comment by bansp** [comment]
Thanks, Tomaž. I take it you've arrived at this issue from the format list, gonna have a look at which centre this is ascribed to.
I'll put in a stub for CoNLL as the "hub" that shouldn't be linked from anywhere (much like, say, "XML" without any subcategorization), and the three stubs, the more so that, AFAIK, e.g. INCEpTION won't grok the extended CoNLL-U (I can't find neither an issue nor an e-mail to this effect, although I seem to recall reporting that).

Apart from that, let just mention the URL for [Universal Anaphora](https://github.com/UniversalAnaphora/UniversalAnaphora/blob/main/documents/UA_CONLL_U_proposal_compact.md), just to have that on record, in case it becomes a format that needs to be mentioned. There's also one for morphological lattices.

**Comment by bansp** [comment]
Fixed in the source, will be uploaded on Tuesday at the latest, and I'll keep the ticket open until then. Thanks a lot!

**Comment by bansp** [comment]
Hmm, we've performed some forestry management in the meantime, as can be seen in this ticket ;-)
Closing, it's all live now, thanks, @TomazErjavec :-)
