### ISSUE TITLE
visualize the formatFamily trees/graphs

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#131]
With reference to #129 , this is an action ticket for visualizing the partial trees built by the `<formatFamily>` elements.
We will obviously need to brainstorm this first.

**Comment by bansp** [comment]
Make it an unlinked page, at first, because lots of errors are to be expected (e.g. ALTO pointing to itself, etc.)

**Comment by margaretha** [comment]
Before we make any visualization, I simply made a table to get an overview of all the `<formatFamily>` entries in the format description file. See [SIS/clarin/views/format-families.xq](https://github.com/clarin-eric/standards/commit/c49fc4ed87d383128b2486655091a5b41a7abcb0#diff-64054b32c584797cfefe0a6c6429bb61b77354dd21a170425e5e48678c2c17d5)
Maybe we can include this in Sanity Check page as well?

It seems that the `<formatFamily>` values are not consistent. Sometimes they refer to other formats, sometimes they indicate some characteristics, keywords, or categories.

When the values refer to other formats, we can treat the formats as nodes and make an edge between them. For each format node, we can also make a hyperlink to the corresponding format page. 

However, it seems that the format values represents `<abbr>` instead of `@id`. I think it would be simpler and more efficient to directly use the IDs.

**Comment by bansp** [comment]
Thanks for approaching this, Eliza. The values indeed aren't consistent, that's why it's so good to check this early, and probably on a page not directly accessible in the production instance -- because it is going to be a mess for a while. And I think definitely not IDs, let's just talk about this when we meet tomorrow, maybe we're talking about different things.

**Comment by margaretha** [comment]
In our meeting, we have decided to
- keep the table
- add a graph visualization
- add a sorting function for each column of the table

**Comment by bansp** [comment]
For convenience, this is a link to the local instance, for testing http://localhost:8889/exist/apps/clarin/views/format-families.xq
This is as complete as can be, and we now have something to work with, thanks Eliza! :-)
