### ISSUE TITLE
Suggestion regarding the description of format ID="fECMA", commitId=7238eb1

### ISSUE THREAD

**Issue by femmynine** [clarin-eric/standards#152]
**Change / add the format description**
At DANS, ECMA is not one of the recommended formats. The link to 'more information' points to the description of RTF on our webpage ([)](https://dans.knaw.nl/en/file-formats/text-documents/rich-text-file-rtf/). Could ECMA please be removed from our list? Many thanks in advance!

**Comment by bansp** [comment]
Hi and thanks. "ECMA" was used as an ID for ECMAscript (standardized Javascript), and the link used there is redirected to RTF by DANS itself, sadly. I'm going to take some action on the SIS-side for that, but I am a bit afraid that you might get quite dismayed when you access https://clarin.ids-mannheim.de/standards/views/view-centre.xq?id=DANS and try to follow the links to "more info" from there. (I'm not going to try that myself, today, because it's the last day of my vacation and I don't want to get too annoyed :-)).

In particular, the link from "fECMA" tries to lead the user to http://dans.knaw.nl/en/about/services/easy/information-about-depositing-data/before-depositing/file-formats/script but if you click on it, you will get redirected. In general, after the restyling of DANS pages, some things look a bit suboptimal -- for example, I was not able to get out of a loop while clicking inside text format recommendations (starting at the link you've provided, https://dans.knaw.nl/en/file-formats/text-documents/rich-text-file-rtf/ ), and even found one dead link there, for a major category. 

SIS is not able to become a (currently) one-man service for handling all the changes in all the centres that wish to change their info pages. It is constructed in such a way as to make it as easy as possible (for a developer, at least) to create a pull request that can be inspected locally, and then pushed online. I'm not saying that should be you :-) , but perhaps there is a representative of DANS who would wish to maintain the info. The SIS doesn't have a chance to work in any other way (and wasn't meant to).

I'll try to address the SIS-internal issues next week, when I'm back at the office. Thanks again for the heads-up!

**Comment by bansp** [comment]
In trying to address this issue further, I have come across the page on HTML: https://dans.knaw.nl/en/file-formats/markup-language/html/ which contains a link to "Javascript" -- the same links as our "ECMA" (now renamed) used, namely https://dans.knaw.nl/en/about/services/easy/information-about-depositing-data/before-depositing/file-formats/script -- that link redirects to a page on RTF (as spotted by @femmynine ) and is a great way to demonstrate to whoever is in charge of DANS information pages that the issue is local to DANS. In general, it seems that, some time after the beginning of 2022 and before the 24th of June: 

- pages were moved to various new paths, partially corresponding to groupings of formats (for example from "en/about/services/easy/information-about-depositing-data/before-depositing/file-formats/xml" to "en/file-formats/markup-language/xml/" or from "en/about/services/easy/information-about-depositing-data/before-depositing/file-formats/sgml" to "bestandsformaten/opmaaktaal/sgml/")
- links in those pages were not modified (or got modified only selectively -- I'm not investigating the extent)
- links in the new main/hub page (https://dans.knaw.nl/en/file-formats/) were updated, so that one is safe to use, for now
- a default (?) redirect exists from some/all dead URLs to, of all the existing possibilities, https://dans.knaw.nl/en/file-formats/text-documents/rich-text-file-rtf/

Action on the side of the SIS was the following:

- putting time into researching the DANS-internal problem of bad and/or missing links (see above)
- renaming the internal ID used for Javascript (=ECMAscript) from "fECMA" to "fJS", to avoid any confusions in the future
- adding a stub describing the format, to make even more clear what is meant by the ID
- changing the old links under `recommendations/DANS` -- to the hub link ("en/file-formats/", see above), thus losing some specificity, but at least not causing errors

In general, we welcome pull requests targeting [`clarin/data/recommendations/DANS-recommendation.xml`](https://github.com/clarin-eric/standards/blob/formats/SIS/clarin/data/recommendations/DANS-recommendation.xml), should anything relevant change in the DANS pages, as part of DANS's commitment to CLARIN (or, if you prefer, as pure courtesy :-)).

**Comment by bansp** [comment]
These changes are now live.
