### ISSUE TITLE
filtering vs. search, search mode (match-left or fulltext), (potentially) a tick-box option for search across long names

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#192]
The screenshot below nicely illustrates all three issues and in a way is a pretext to keep all three of them together (I can imagine that they might be quick to handle).

![image](https://user-images.githubusercontent.com/312137/223482122-879707c2-0231-49f4-93b4-6e5caba1e9a5.png)

1. Firstly, it seems that the search should be full-text, rather than matching from the left edge (so, "DI" should probably also result in "CMDI") -- **OR** we could have a tick-box for "full-text search". (but maybe a tick-box is overkill, here)
2. Secondly, mixing short and long names was a very good idea, overall, but, since sometimes the long names are quite unexpected (and in some cases quite unknown), maybe we could have a tick-box for that, as well? Like "match long names".
3. Thirdly, it might be an intuitive expectation that the domain of the search is responsive to filtering, so it only searches in all format names if no filtering has been performed, and otherwise it searches across the filtered results.

Now, briefly, what I think should NOT happen is:
1. "DICOM" shouldn't come up, because it is not among the formats filtered for
2. *maybe* the long name (Digital Imaging and Communications in Medicine) shouldn't come up if not requested (let's talk about that)

What should happen:
1. "CMDI" should be matched by "DI" (we can discuss whether that should always be the case, or only by request)

By "full-text" above I don't mean e.g. the possibility of globbing with "*" or using regular expressions. I rather mean that "DI" (perhaps) should be treated as if it were "*DI*" in full-text searches. Matching along the string, not anchored on the left side.

**Comment by bansp** [comment]
Eliza: tick-box is too much. Eliza will modify the way search works: (a) full-text and (b) restricted according to the filter (= to the table).

**Comment by bansp** [comment]
This requires further work so we are pushing it to 2.6.0.

**Comment by margaretha** [comment]
The search field now functions like an extended filter of the recommendation table. I have implemented the full text search and the extended filter, i.e. search is limited only to the current table content. I also removed "title" from the search suggestions. 

There are some remaining issues.

1. The search suggestions includes format-ids which I think not very user-friendly but it is useful for formats that have not been described yet in SIS, thus do not have abbreviations.

2. Export has not been updated with the extra filtering by using the search form. For the filter and search example below, the export file would still include all recommendations with Audiovisual Annotation and Audiovisual source domains from other centres.

![image](https://user-images.githubusercontent.com/5528620/231195851-ecd7d2fd-2344-4632-a71f-48c3114933db.png)

It should probably also be limited to DANS only. The question is how should we describe the extra filtering from search form? This also requires changes in the recommendation scheme.

Suggestion:

* adds a search element in the filter 

```
<header>
  <title>CLARIN Standards Information System (SIS) export</title>
  <url>http://localhost:8889/exist/apps/clarin/views/recommended-formats-with-search.xq</url>
  <exportDate>2023-04-11T16:37:32.48+02:00</exportDate>
  <filter>
    <domain>Audiovisual Annotation</domain>
    <domain>Audiovisual Source Language Data</domain>
    <search>DANS</search>
  </filter>
</header>
```

Since the search value can also be a domain, it is possible to have such a filter:

```
<header>
  <title>CLARIN Standards Information System (SIS) export</title>
  <url>http://localhost:8889/exist/apps/clarin/views/recommended-formats-with-search.xq</url>
  <exportDate>2023-04-11T16:37:32.48+02:00</exportDate>
  <filter>
    <domain>Audiovisual Annotation</domain>
    <domain>Audiovisual Source Language Data</domain>
    <search>Audiovisual Annotation</search>
  </filter>
</header>
```

**Comment by bansp** [comment]
@bansp see if some stuff from here should go into new issues and then close the ticket

**Comment by bansp** [comment]
If I'm not wrong, the outstanding issue is to modify the schema, so that a `<search>` element is allowed, correct? That should be a quick one.
