### ISSUE TITLE
keep centre data together... move the "info" field into the recommendations

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#196]
This is a little step but it may avoid a lot of confusion and potential bad blood: let's move the content of the `<info>` field in  https://github.com/clarin-eric/standards/blob/formats/SIS/clarin/data/centres.xml to the respective recommendation files.

This way, we will be asking centre representatives to only edit a single file, and especially if they do not fork but just export-and-edit, they will have all the info within easy reach. Otherwise, their life, and often, as a consequence, our life, may get a bit more complicated, and there's every reason to try to avoid that.

If @margaretha agrees to this, it will require a bit of synchronisation from us: I should modify the schemas and move the relevant fields over (or create empty `info` elements -- that's a no-brainer), and then Eliza would adjust the visualisation (or I can start and Eliza will check and fix the result).  (At some points, we'll need to handle the default templates; and maybe modify the `sort-format.xq` script).

I would love to have this in before the first inputhon, unless Eliza objects. Adding to 2.5.0, pending potential discussion. Assigning first to myself but waiting for green light from Eliza.

**Comment by margaretha** [comment]
There won't be technical problems with moving the `<info>` field, I suppose. But where should it go?

We cannot put the `info` closely to `centre` since `centre` is only indicated as a filter. But maybe we can treat the `info` as recommendation info.

With these changes, we need to remove description from `view-centre.xq` and include the `info` in the exported recommendation file.

Good that you mentioned sort-format.xq! It doesn't need any changes, if we put `info` within `header`. But if it needs changes is also fine. It shouldn't take much effort.

**Comment by bansp** [comment]
This ticket has two parts: schema for Piotr and retrieving the info from a different place (not centres.xml but recommendations for the given centre), for Eliza. 
Piotr will modify the schema immediately after the meeting (28-mar-2023).

**Comment by bansp** [comment]
Schema-part handled, our only `<info>` so far relocated under the appropriate recommendations. Un-assigning myself then.
