### ISSUE TITLE
Suggestion regarding the description of format ID="fLMF", commitId=5bbdae9

### ISSUE THREAD

**Issue by mmatthiesencsc** [clarin-eric/standards#257]
**Add / correct the following fields**
- Long name: LMF Lexical Markup Framework
- Keywords: Lexical Markup
- File extension: lmf
- Media type: text/x-lmf+xml
- Format family: Lexical file formats
- Standard that defines or uses the format:  ISO 24613-1

**Comment by bansp** [comment]
Dear @mmatthiesencsc thanks again for your contributions! 
@margaretha has kindly encoded them and will add them to the live instance very soon.

I wonder: since you're referencing the updated standard, with "-1", you may mean the TEI format defined by the appropriate subpart (4) https://www.iso.org/standard/75411.html -- do you? Or do you have something else in mind, maybe the old LMF serialisation (it might happen that some data in the old format are still out there). 

Hmm, gosh, some of that data must float around still, and it's really good to have an anchor for it. The old standard is https://www.iso.org/standard/37327.html (ISO 24613:2008). We'll get that handled.

**Comment by mmatthiesencsc** [comment]
Yes, I meant subpart 4, good you caught it:
Standard that defines or uses the format: ISO 24613-4
Full disclosure, not an expert, tried my best to propose something meaningful.

**Comment by bansp** [comment]
Ahh, glad I asked -- I thought you may have referred to the old LMF format that, who knows, might still be floating around, given that there used to be a CLARIN tool using it, once.

I'll leave this issue open for now, to make sure to possibly add to the file that Eliza has created. Thanks again!

**Comment by mmatthiesencsc** [comment]
@margaretha @bansp : I am really not the expert here, but should the Description not read: See ISO 24613**-4** ?

**Comment by margaretha** [comment]
@mmatthiesencsc Thanks for your remark. I have updated it.

**Comment by bansp** [comment]
The conversation in PR #264 is somewhat related to this item. (Need to create two LMF format info documents).
