### ISSUE TITLE
Add FST format

### ISSUE THREAD

**Issue by OyvindLGjesdal** [clarin-eric/standards#276]
This template is linked from several places in the SIS. Please feel encouraged to delete the fields below that are irrelevant to your report (including this lead text).

**Format short name / ID** 
fFST
Formats that have descriptions in the SIS  are best identified by their internal IDs, otherwise please use a name that identifies the format well (we will supply the ID). Feel welcome to remove this section if the ID is auto-referenced in the title of this issue.

**Add / correct the following fields**
- Long name: Finite state transducer source code
- Keywords: Regular expressions, finite state transducer, XFST, HFST
- File extension: .regex
- Media type:  text/plain
- Format family: 
- Standard that defines or uses the format: The format is used by the XFST and HFST tools. 
- (Optional) description:
See "Kenneth R. Beesley and Lauri Karttunen, Finite-State Morphology, 2003"
**Change / add the format description**
We would like to add this format for the CLARINO bergen center.

**Comment by bansp** [comment]
Would this link be OK as a publicly available reference/illustration? 
https://github.com/hfst/hfst/wiki/HfstXfst

**Comment by bansp** [comment]
I have also added FST to the "Tool Support" domain -- is that OK, or do you have strong feelings in this respect?
The domain descriptions are at https://standards.clarin.eu/sis/views/list-domains.xq , and I'm bothered by the presence of ZIP, TAR, etc. there. 

Otherwise, source code, init files, schemas and CSS are the natural (?) members of that domain, and I have a feeling that FST fits in as well -- what do you think, please? Or should it remain in "Lexical Resource" (whose definition is not exactly there, I feel: "Structured (item-based) resources for lexical and/or conceptual information on units of language (e.g. wordlists, lexicons, WordNets etc.)")?

**Comment by paulmeurer** [comment]
After reading the domain descriptions, I also think that the “Tool Support” domain is well suited for FST source code files.

**Comment by bansp** [comment]
Thank you both! It's all going online tomorrow.

**Comment by bansp** [comment]
Online at https://standards.clarin.eu/sis/views/view-format.xq?id=fFST , closing the issue.
