### ISSUE TITLE
Interoperability with other format descriptions

### ISSUE THREAD

**Issue by hannahedeland** [clarin-eric/standards#56]
We could maybe just focus on LRT specific formats and reuse existing sources like the Format Definition Documents of the Library of Congress (cf. https://www.loc.gov/preservation/digital/formats/fdd/fdd_xml_info.shtml) for more generic formats. 

FAIRSharing.org also includes some relevant "community standards", though it's not as transparent and the new version is currently beta, so this would probably rather be something for the other direction, at a later stage.

**Comment by bansp** [comment]
Thanks! It would be very sensible indeed to use the LoC for the outside of LRT, and FAIRSharing for, say, outreach. Keeping to our assumptions (scope on CLARIN and bottom-up reports, medium granularity), we'd probably just use a link to the relevant bit of the LoC inside a skeleton of a format-description file (which needs to specify the ID, the mimeType, and the extension, minimally). I think that should help a lot, indeed, because otherwise coping with all those 'outside' formats could become a nightmare.

**Comment by bansp** [comment]
That was for whatever, although Eliza has since merged that PR ;-) 
But formats is a good target anyway, or you can set up another branch -- take the most convenient way out.

**Comment by bansp** [comment]
We can probably close this one (because it has a concrete task ticket now). Fairsharing has not been handled yet; indeed, it may be a candidate for "the other way round".

**Comment by bansp** [comment]
Aaaand, thanks to @hannahedeland 's suggestion above, we now even have a Fairsharing ID... :-) https://fairsharing.org/4705

**Comment by bansp** [comment]
Well, not really a wontfix, because the issue has served its purpose. Closing with thanks.
