### ISSUE TITLE
catch the date of the last commit and encode it in the header of the recommendations file

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#81]
With reference to #45 , have a hook that catches the date/time of the commit and encodes it in the header of the recommendations file.

**Comment by margaretha** [comment]
I think it is better to call it <lastUpdate> then <lastCommit> because the date should only be updated when the format content is really updated, not necessarily for every commit. Because when a script add or change the <lastUpdate> element, there will be a new commit for that. 

So the hook should only be run when there is changes in the format content, e.g.  when there is a pull request from a centre representative, or changes from developers.

**Comment by bansp** [comment]
Updated #44 accordingly.

**Comment by margaretha** [comment]
Maybe it is enough to put commitId to the `<lastUpdate>` instead of date of the commit.

**Comment by bansp** [comment]
Just to make things clear (we're in a meeting right now): we're talking about manually handling a commit ID that is significant for the state of information, rather than the very last commit ID.

**Comment by bansp** [comment]
`<lastUpdateCommitID>` ?
