### ISSUE TITLE
minor fixes for CLARINSI and BAS

### ISSUE THREAD

**Issue by hannahedeland** [clarin-eric/standards#83]
CLARINSI has EXMA -> EXB + EXS
BAS has DC-XML -> DCXML
We should then also get rid of fEXMA and fDC-XML, or does this happen automatically?

**Comment by bansp** [comment]
The message is a bit too compressed, I don't fully understand... :-)
"Get rid" from where? Could you perhaps do a PR, so that it's clearer? 

* if you're referring to the list of "wanted" formats -- these are extracted from recommendations
* so if you remove all mentions of some such ID from all recommendations, then the ID will disappear from the "wanted" list

**Comment by hannahedeland** [comment]
yes, well i guess from that list, i wasn't quite sure if there would be some orphaned formats left if they were only removed from recommendations, i'll take care of this one then, though i should maybe rather switch to DC-XML since hyphen seems to be the standard solution (e.g. DGD-XML, CHAT-XML)?

**Comment by bansp** [comment]
Yep, with a hyphen it looks a bit better, I think.
Thanks!

**Comment by bansp** [comment]
Fixed in 6e531e9e13111ef082a3b1be33ad9d7866c1cae2
